import React from 'react';
import teamImage from '../assets/team.png';
import { FaGithub, FaLinkedin, FaEnvelope, FaGlobe } from 'react-icons/fa';
import { SiGooglescholar } from 'react-icons/si';
import './TeamSection.css';

const TeamSection: React.FC = () => {
  return (
    <div className="team-container">
      <h2>Our Team</h2>
      
      <div className="team-content">
        <div className="team-image">
          <img src={teamImage} alt="Team members - three pilots" />
        </div>
        <p>Image Generated by ChatGPT.</p>
        
        <div className="team-members">
          <div className="team-member">
            <h3>Aryan Ahadinia</h3>
            <p>MSc in CS, EPFL</p>
            <div className="social-icons">
              <a href="mailto:aryan.ahadinia@epfl.ch" title="Email" className="social-icon">
                <FaEnvelope />
              </a>
              <a href="https://people.epfl.ch/aryan.ahadinia/?lang=en" target="_blank" rel="noopener noreferrer" title="Homepage" className="social-icon">
                <FaGlobe />
              </a>
              <a href="https://github.com/AryanAhadinia" target="_blank" rel="noopener noreferrer" title="GitHub" className="social-icon">
                <FaGithub />
              </a>
              <a href="https://www.linkedin.com/in/ahadinia/" target="_blank" rel="noopener noreferrer" title="LinkedIn" className="social-icon">
                <FaLinkedin />
              </a>
              <a href="https://scholar.google.com/citations?user=C5-a0JIAAAAJ&hl=en" target="_blank" rel="noopener noreferrer" title="Google Scholar" className="social-icon">
                <SiGooglescholar />
              </a>
            </div>
          </div>
          
          <div className="team-member">
            <h3>Matin Ansaripour</h3>
            <p>MSc in CS, EPFL</p>
            <div className="social-icons">
              <a href="mailto:matin.ansaripour@epfl.ch" title="Email" className="social-icon">
                <FaEnvelope />
              </a>
              <a href="https://people.epfl.ch/matin.ansaripour?lang=en" target="_blank" rel="noopener noreferrer" title="Homepage" className="social-icon">
                <FaGlobe />
              </a>
              <a href="https://github.com/matinansaripour" target="_blank" rel="noopener noreferrer" title="GitHub" className="social-icon">
                <FaGithub />
              </a>
              <a href="https://ch.linkedin.com/in/matin-ansaripour-b2b7a81a3" target="_blank" rel="noopener noreferrer" title="LinkedIn" className="social-icon">
                <FaLinkedin />
              </a>
              <a href="https://scholar.google.com/citations?user=cFb2pzMAAAAJ&hl=en" target="_blank" rel="noopener noreferrer" title="Google Scholar" className="social-icon">
                <SiGooglescholar />
              </a>
            </div>
          </div>
          
          <div className="team-member">
            <h3>Parsa Neshaei</h3>
            <p>EDIC, EPFL</p>
            <div className="social-icons">
              <a href="mailto:seyed.neshaei@epfl.ch" title="Email" className="social-icon">
                <FaEnvelope />
              </a>
              <a href="https://people.epfl.ch/seyed.neshaei/?lang=en" target="_blank" rel="noopener noreferrer" title="Homepage" className="social-icon">
                <FaGlobe />
              </a>
              <a href="https://github.com/spneshaei" target="_blank" rel="noopener noreferrer" title="GitHub" className="social-icon">
                <FaGithub />
              </a>
              <a href="https://ch.linkedin.com/in/spneshaei" target="_blank" rel="noopener noreferrer" title="LinkedIn" className="social-icon">
                <FaLinkedin />
              </a>
              <a href="https://scholar.google.com/citations?user=hZFxf-kAAAAJ&hl=en" target="_blank" rel="noopener noreferrer" title="Google Scholar" className="social-icon">
                <SiGooglescholar />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TeamSection; 